src/modalities/loss_functions.py, tests/test_loss_functions.py
This PR contains the implementation and test for noise contrastive estimation loss for training multimodal models . Code adapted from (https://arxiv.org/pdf/1912.06430.pdf)
=> Add Noise Contrastive Estimation Loss

src/modalities/evaluator.py, src/modalities/trainer.py, tests/test_gym.py
Attempts to fix the testing part of #28 (i.e. unit testing on CPU) by
- replacing `torch.device(self.local_rank)` by `torch.device(self.local_rank) if torch.cuda.is_available() else "cpu"`
- removing the mocking of the "reduce" operation which causes `test_gym.py` to fail
=> fix: tests on cpu

config_files/data_preparation/packed_cc_en_2048.yaml, src/modalities/__main__.py, src/modalities/config/config.py, src/modalities/dataloader/create_packed_data.py
On DGX the PackedDataGenerator was quite slow with throughput ranging between 30 - 300 samples/second. 
The PR adds queuing, batching and rate limiting, resulting in more than 20.000 samples / second.
=> Improving throughput for PackedDataGenerator

config_files/training/config_lorem_ipsum.yaml, src/modalities/models/gpt2/gpt2_model.py
we experienced loss convergence to almost 0 while inference performance was rather low. 
We figured, there was an information leakage bug due to view and reshape operations that lead to parts of embeddings of different tokens being mixed.
=> fix: fixed  tensor reshape operations

src/modalities/models/gpt2/gpt2_model.py
This PR fixes the pre-LN by reverting the changes (accidentally?) introduced [here]( https://github.com/Modalities/modalities/commit/8dd74a4f98968be85c1600200cb6fd0aa5700553#diff-7b510b8da861fb91767d9aefe8db60e8ee5ae624aec986b7dc36da5f34ed48adL207)
References:
- Fig.1 & Tab. 1 in the paper [On Layer Normalization in the Transformer Architecture](https://arxiv.org/abs/2002.04745)
- [nanoGPT](https://github.com/karpathy/nanoGPT/blob/master/model.py#L103)
=> Fix Pre-LN for GPT2 Model

config_files/training/config_lorem_ipsum.yaml, src/modalities/models/gpt2/gpt2_model.py, tests/models/test_causal_self_attention.py, tests/test_yaml_configs/config_lorem_ipsum.yaml
This PR implements `manual attention` and `pytorch flash attention`, in addition to the previously implemented `dao flash attention`. Group Query Attention is supported.
=> Implementation of multiple attention mechanisms

config_files/training/config_lorem_ipsum.yaml, src/modalities/config/component_factory.py, tests/config/test_component_factory.py
Implemented verification that all required attributes are set and not more than optional + required attributes are present.
The does not use Pydantics verification methods, but implements the check in native python. This allows for a very clear error message about the configuration. 
With this fix, the misconfigured config
```yaml
batch_progress_subscriber:
component_key: progress_subscriber
variant_key: rich
```
was fixed.
=> fix: #97 Unused attributes in a component's config yaml are just ignored by Pydantic

config_files/training/config_example_coca.yaml, pyproject.toml, src/modalities/models/coca/coca_model.py, src/modalities/models/coca/multi_modal_decoder.py, src/modalities/models/coca/text_decoder.py, src/modalities/models/gpt2/gpt2_model.py, src/modalities/models/huggingface/huggingface_models.py, src/modalities/models/mamba/mamba_block.py, src/modalities/models/mamba/mamba_model.py, src/modalities/models/mamba/ops/selective_scan_interface.py, src/modalities/models/mamba/ops/triton/layernorm.py, src/modalities/models/mamba/ops/triton/selective_state_update.py, src/modalities/models/mamba/utils/generation.py, src/modalities/models/model.py, src/modalities/registry/components.py, src/modalities/running_env/fsdp/fsdp_auto_wrapper.py, src/modalities/tokenization/tokenizer_wrapper.py, tests/config/test_component_factory.py, tests/models/mamba/conftest.py, tests/models/mamba/test_mamba_block.py, tests/models/mamba/test_mamba_model.py, tests/test_yaml_configs/config_lorem_ipsum.yaml
This PR fixes a few issues introduced mainly (but not exclusively) by #113:
- missing dependencies for Mamba (ce9d3fe)
- failed unit tests due to outdated test config files (fe439ca)
- global reformatting / linting, mainly of Mamba-related modules (e86fd86). 
The last change was probably necessary as the pre-commits in `pyproject.toml` had been commented out in #113, see [here](https://github.com/Modalities/modalities/pull/113/commits/1c90de3e71c3ea483f427eddf233bbe449c3c5f0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711).
=> Various small fixes for Mamba, unit tests & linting

src/modalities/__main__.py, src/modalities/checkpointing/fsdp/fsdp_checkpoint_loading.py, src/modalities/dataloader/dataloader_factory.py, src/modalities/optimizers/optimizer_factory.py, src/modalities/running_env/cuda_env.py, src/modalities/trainer.py, tests/checkpointing/gpt2_config.yaml, tests/checkpointing/test_fsdp_to_disc_checkpointing.py, tests/checkpointing/torch/test_torch_checkpoint_loading.py, tests/dataloader/distributed/dist_dataloader_config_with_shuffling.yaml, tests/dataloader/distributed/dist_dataloader_config_with_shuffling_and_skipped_batches.yaml, tests/dataloader/distributed/dist_dataloader_config_without_shuffling.yaml, tests/dataloader/distributed/dist_repeating_dataloader_config_without_shuffling_but_skipped_batch.yaml, tests/end2end_tests/gpt2_train_num_steps_8.yaml, tests/end2end_tests/gpt2_warm_start_from_step_4.yaml, tests/end2end_tests/test_fsdp_warmstart.py, tests/models/test_causal_self_attention.py, tests/run_distributed_tests.sh, tests/test_optimizer_factory.py, tests/test_yaml_configs/gpt2_config_optimizer.yaml, tests/tests.py
This PR
Examples:
- `python tests/tests.py`: run CPU tests + single-GPU tests on GPU 0 + multi-GPU tests on GPUs 0/1
- `python tests/tests.py --devices 4,5`: same as above but using devices 4/5
- `python tests/tests.py --cpu`: run CPU tests
- `python tests/tests.py --single-gpu --devices 3`:  run CPU tests + single-GPU tests on GPU 3 
- `python tests/tests.py --multi-gpu --devices 3,4`: run multi-GPU tests on GPUs 3/4
Note that any GPU device 0-7 can be specified.
=> Unified unit & end-to-end testing

config_files/training/config_example_coca.yaml, config_files/training/config_example_hf_meditron_7B_instruction.yaml, config_files/training/config_gpt2_small_overfitting_de.yaml, config_files/training/config_gpt2_small_overfitting_de_abs_pos_emb.yaml, config_files/training/config_gpt2_small_redpajama_DE_1048576.yaml, config_files/training/config_lorem_ipsum.yaml, config_files/training/config_mem_map_mamba.yaml, config_files/training/config_mem_map_mamba_overfitting.yaml, config_files/training/config_mem_map_mamba_small_scale.yaml, pyproject.toml, src/modalities/__main__.py, src/modalities/activation_checkpointing.py, src/modalities/config/instantiation_models.py, src/modalities/running_env/fsdp/fsdp_auto_wrapper.py, src/modalities/util.py, tests/models/coca/coca_config.yaml
This PR addresses the issue described in [Issue #32](https://github.com/Modalities/modalities/issues/32) by removing the hard-coded dependency for applying activation checkpointing specifically to `GPT2Block`. Instead, activation checkpointing is now made configurable through the configuration file, allowing greater flexibility and adaptability for different models.
**General changes:**
* Enhancement: Allow the definition of modules to be checkpointed within the configuration file
**Breaking changes:** 
* Enhacement: make modules to be checkpointed configurable.
This requires replacing the boolean entry `do_apply_activation_checkpointing` in the configuration file with the list `activation_checkpointing_modules` (see 4a2a049e893acdd49c2dd7801b74a20af0db1e38), which specifies all the …
=> Make Activation Checkpointing Configurable

.github/workflows/tests.yml, pyproject.toml
This PR fixes #173 by 
* restricting the supported python versions to 3.10 and 3.11
* extending unit testing to 3.11.
* none apart from the above
* none
=> Support and test python versions 3.10 and 3.11

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/config.yaml, .github/ISSUE_TEMPLATE/documentation.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml, .github/pull_request_template.md
This PR 
* improves the current pull request template
* adds several issue templates (bug report, documentation, feature request, blank)
* none apart from the above
* none
=> Pull Request & Issue Templates

src/modalities/config/config.py, src/modalities/util.py
This PR ensures that experiment IDs are unque.
* Append a hash value that is build based on the config file path to the experiment ID
* None
=> feat: Unique Experiment ID

src/modalities/__main__.py, src/modalities/checkpointing/torch/torch_checkpoint_loading.py, src/modalities/logging_broker/subscriber_impl/results_subscriber.py, src/modalities/models/model_factory.py, src/modalities/optimizers/optimizer_factory.py, src/modalities/util.py, tests/test_utils.py, tests/test_yaml_configs/config_lorem_ipsum.yaml
This PR updates the computation of the total number parameters in a (sharded) model.
Previously, the parameter count only reflected the number of parameters in a single shard wher the model was sharded.
* All ranks collectively reduce the total number of parameters.
* None
=> Fix: Computation of Total Number of Parameters

config_files/training/config_example_coca.yaml, config_files/training/config_lorem_ipsum.yaml, examples/library_usage/config_lorem_ipsum.yaml, src/modalities/__main__.py, src/modalities/config/config.py, src/modalities/evaluator.py, src/modalities/logging_broker/subscriber_impl/subscriber_factory.py, src/modalities/trainer.py, tests/conftest.py, tests/test_evaluator.py, tests/test_yaml_configs/config_lorem_ipsum.yaml
Previously, the logging was performed on all local ranks == 0, leading to excessive logging in multi-node training. We fixed this issue and log now only on a single rank, i.e., global rank == 0.  
* see above
* The config now expects global ranks for the loggers now. See the changes [her](https://github.com/Modalities/modalities/commit/aa73dce73650d0fcc9a59a484667b198b3e91c17).
=> Fix log only with global rank 0

src/modalities/config/config.py, src/modalities/config/instantiation_models.py, src/modalities/nn/model_initialization/composed_initialization.py
This PR fixes pydantic warnings like `UserWarning: Field "model_initializer" has conflict with protected namespace "model_"` (see #108) in the same way as #109. This should probably be considered a quick fix rather than a permanent solution (see #200).
none except for the above
none
=> Fix pydantic warnings about model_ namespace

src/modalities/__main__.py, src/modalities/gym.py, src/modalities/util.py
This PR introduces logging for critical stages in the training pipeline, specifically during model initialization and the start and end of model training. These enhancements aim to improve the transparency, debuggability, and traceability of the model lifecycle events, facilitating easier monitoring and troubleshooting.
* Log time and date for specific lifecycle events.
* None.
=> feat: log model initialization & training start/end

tests/conftest.py
This PR fixes #203.
The problem was caused by a breaking change in torch 2.4 regarding the way caching of `device_count` works, compare https://pytorch.org/docs/2.3/_modules/torch/cuda.html#device_count and https://pytorch.org/docs/2.4/_modules/torch/cuda.html#device_count
none except for the above
none
=> Fix CPU Tests with Github Actions for torch>=2.4

tests/test_utils.py
This PR is a follow-up to #216. It
* fixes linting in `test_utils.py`
* replaces the automated parameter counting by manual parameter counting in `test_get_local_number_of_trainable_parameters`. Automated parameter counting seems a bit meaningless since it literally uses the same line of code as the tested function.
none except for the above
none
=> Fix linting & improve test_utils

src/modalities/models/coca/attention_pooling.py, src/modalities/models/coca/coca_model.py, src/modalities/models/coca/collator.py, src/modalities/models/coca/multi_modal_decoder.py, src/modalities/models/coca/text_decoder.py, src/modalities/models/components/layer_norms.py, src/modalities/models/gpt2/collator.py, src/modalities/models/gpt2/gpt2_model.py, src/modalities/models/gpt2/pretrained_gpt_model.py, src/modalities/models/huggingface/huggingface_model.py, src/modalities/models/huggingface_adapters/hf_adapter.py, src/modalities/models/mamba/mamba_block.py, src/modalities/models/mamba/mamba_config.py, src/modalities/models/mamba/mamba_model.py, src/modalities/models/mamba/ops/selective_scan_interface.py, src/modalities/models/mamba/ops/triton/layernorm.py, src/modalities/models/mamba/ops/triton/selective_state_update.py, src/modalities/models/mamba/utils/generation.py, src/modalities/models/model.py, src/modalities/models/model_factory.py, src/modalities/models/utils.py, src/modalities/models/vision_transformer/vision_transformer_model.py
This PR adds docstrings to all model related modules, enhancing code documentation and readability.
* 
* None
=> Docstrings Models

tests/run_all_tests.sh, tests/run_distributed_tests.sh, tests/tests.py
This PR is a follow-up to #241 and fixes a few minor things:
* validity of 3rd input argument (`--cov / --no-cov`) in `run_distributed_tests.sh` is checked
* `run_distributed_tests.sh` is called with `--no-cov` from `tests/tests.py`
* unused 3rd input argument in `run_all_tests.sh` is removed
* none
* none
=> Fix run test scripts

src/modalities/checkpointing/checkpoint_saving_strategies.py, tests/checkpointing/test_checkpoint_strategies.py
The list of `saved_step_checkpoints` contains TrainingProgress objects which are *references* to the TrainingProgress objects, which are updated during training. So all elements in the list will be the same, and will correspond to the current progress. Thus, in cases where `k > 0`, only the first k checkpoints are saved, and all remaining checkpoints are created and immediately deleted (since the `checkpoints_to_delete` is the same as the most recently saved one).  
Solution: clone TrainingProgress object when saving the list of saved checkpoints.
* fixed as above
* added an assert in the test to check for this case
none
=> fix: clone TrainingProgress when saving list of saved checkpoints

CHANGELOG_DEV.md, src/modalities/dataloader/create_packed_data.py, tests/dataloader/test_packed_dataset.py
This PR fixes the bytes per token calculation.
Generally, we estimate how many bytes are needed to encode the full range of the vocabulary. 
E.g., for a vocab size > 65536, we need 3 bytes for each token in the pbin file. 
The calculation was wrong but coincidentally correct for the GPT2 tokenizer.
=> Bugfix: the number of bytes per token were wrongly calculated

CHANGELOG_DEV.md, src/modalities/__main__.py, src/modalities/api.py, src/modalities/dataloader/create_index.py, src/modalities/dataloader/create_packed_data.py, tests/dataloader/test_large_file_lines_reader.py
The char-based index is not always consistent with the byte-based index.
For instance, the first character of the string "ø This is..." is written on disc as two bytes, namely \xc3\xb8, when encoded as utf-8. 
Therefore, the byte-based index has one more byte/char than the char-based index. 
For consistency, we don't consider any char-based indexes anymore and always refer to byte-based indexes. 
- [] I have merged the latest version of the target branch into this feature branch
=> Bugfix: char-based index and byte-based index mismatch

CHANGELOG_DEV.md, src/modalities/__main__.py, src/modalities/api.py, src/modalities/dataloader/create_index.py, src/modalities/dataloader/create_packed_data.py, tests/dataloader/test_large_file_lines_reader.py, tests/dataloader/test_packed_dataset.py
Previously, the number of bytes per token was calculated by `math.ceil(log_2(vocab_size)/8)`, leading to ranges between 1 and 4 bytes. 
However, the dataset implementation only support 1, 2 and 4 bytes per token, as defined here
https://github.com/Modalities/modalities/blob/0483362abac93e45850e56adaea7921e96836d59/src/modalities/dataloader/dataset.py#L202-L206
and 
https://github.com/Modalities/modalities/blob/0483362abac93e45850e56adaea7921e96836d59/src/modalities/dataloader/dataset.py#L233-L234
I added a switch case that maps to the respective byte sizes, when packing the data.
This adds some inefficiencies as a vobabulary size > 65536 already requires 4 bytes per token, effectively doubling the storage requirements. 
- [] I have merged the latest version of the target branch into this …
=> bug fix: Enforce power of 2 number of bytes per token

src/modalities/models/coca/multi_modal_decoder.py, src/modalities/models/gpt2/gpt2_model.py, src/modalities/models/model.py, tests/nn/test_mlp.py
This PR introduces a change to the SwiGLU activation by making the hidden dimension configurable. Previously, the hidden dimension was fixed (4 * `n_embd`), limiting flexibility in customizing the model architecture especially when using group query attention. This update enhances the usability of SwiGLU by allowing users to specify a custom hidden dimension during initialization.
* Add `ffn_hidden` to the SwiGLU module.
* None
=> Make Hidden Dimension Configurable For SwiGLU

src/modalities/__main__.py, src/modalities/dataloader/shuffle_tokenized_data.py, tests/conftest.py, tests/dataloader/test_shuffle_tokenized_data.py
This PR introduces functionality to shuffle both the data and index segments in a packed file format. The primary goal is to eliminate the reliance on random reads during later stages when the data is accessed via mmap.
By shuffling the index and aligning it with a shuffled byte stream of the data, this implementation ensures that data can be read sequentially. 
The `shuffle_tokenized_data` function loads the input data and index into memory, shuffles the index entries, and processes them in batches to recduce the memory footprint. 
None.
=> Shuffle Tokenized Data

src/modalities/models/gpt2/gpt2_model.py, tests/test_yaml_configs/config_lorem_ipsum.yaml
=> feat: Make RoPE Base Frequency Configurable

.gitignore, .pre-commit-config.yaml, src/modalities/config/config.py, src/modalities/dataloader/shuffle_tokenized_data.py, src/modalities/registry/components.py, tests/dataloader/samplers/test_sequential_samplers.py
This PR adds a `SequentialSampler` component.
Before, we only had a `ResumableDistributedSampler` which distributes the samples among all ranks (disjoint sets). For very small datasets this `ResumableDistributedSampler` leads to incomplete batches (or even empty batches on some ranks) when scaling up the ranks. 
As a workaround, the `SequentialSampler` can be used which replicates the data on all ranks instead. This way, the same loss is computed  on each rank. Since we always calculate the per-token loss, this has no effect on the total loss.
=> Added sequential sampler

src/modalities/models/huggingface_adapters/hf_adapter.py, tests/checkpointing/test_checkpoint_conversion.py
Fixed error caused by changes to transformer library. Also added skip conditions for hf adapter tests so that they are less likely to be skipped.
* Error fix
* Modified skip condition for corresponding tests:
* Only 1 GPU required instead of 2 GPUs and RANK environment variable being set.
=> Fixed error in huggingface adapter.

tests/models/test_model_factory.py
This PR adresses https://github.com/Modalities/modalities/issues/337 by adding a unit test for the `get_fsdp2_wrapped_model` method in `ModelFactory.` The test ensures that:
- The correct module class is resolved based on `block_names`.
- The `fully_shard` function is called on each matching block and the full model.
- The correct sharding arguments (e.g., mesh, reshard_after_forward) are passed during wrapping.
Note: The output of the method returns the original model (as expected with the mocked setup).
-
None.
=> test: Implement test for get_fsdp2_wrapped_model

tests/models/test_model_factory.py
This PR addresses https://github.com/Modalities/modalities/issues/338 by implementing unit tests for the `_is_model_on_meta_device` static method in `ModelFactory.`
The tests cover the following cases:
- All parameters and buffers on the meta device → returns `True`
- All parameters and buffers on a regular device (e.g., CPU) → returns `False`
- Mixed setup (some on meta, some not) → raises `ModelStateError`
* 
* None.
=> Test whether model is on meta device

src/modalities/models/gpt2/gpt2_model.py, src/modalities/models/model.py, src/modalities/models/model_factory.py
This PR fixe an issue that occurs when using SwiGLU in a FSDP2 + TP combination. 
Since the hidden dim is computed dynamically to compensate for the difference in the number of trainable weights in comparison to GeLU, we end up with hidden dims that are not a multiple of the world size. 
This in return creates a problem when applying TP and subsequently FSDP2, as uneven sharding is not allowed for FSDP2 + TP (yet). The issue does not occur when only using FSDP2, as FSDP2 already support uneven sharding out of the box. 
* ..
* .. 
- [] I have merged the latest version of the target branch into this feature branch
=> Fix of SwiGLU hidden not being multiple of world size
