- config_files/config_example_hf_meditron_7B_instruction.yaml
- config_files/config_example_mem_map_dataset.yaml
- config_files/config_lorem_ipsum.yaml
- src/modalities/__main__.py
- src/modalities/config/config.py
- src/modalities/trainer.py
- src/modalities/utils/gradient_clipping.py
- tests/conftest.py
- tests/utils/test_gradient_clipping.py
> Added gradient clipping to training.

- src/modalities/trainer.py
Previously with gradient accumulation, the loss was divided by the number of gradient accumulation steps. This normalised loss was then logged. From a logging perspective,  each train step is equivalent to one gradient accumulation step and therefore the normalisation was not needed. 
Additionally, I refactored the gradient clipping in two ways. Firstly, we were not using the FSDP gradient clipping. This is now integrated but needs to be made configurable. This I will do in another PR. 
Secondly, the gradient clipping is only calculated and logged after # gradient accumulation steps. Since garden clipping already syncs the gradient norm across all the ranks, we don't have to apply the reduce operation on them anymore.
> refactor: fixed loss logging during gradient accumulation and gradient clipping

- config_files/training/config_example_coca.yaml
- config_files/training/config_lorem_ipsum.yaml
- src/modalities/config/config.py
- src/modalities/logging_broker/subscriber_impl/results_subscriber.py
- src/modalities/logging_broker/subscriber_impl/subscriber_factory.py
- tests/test_yaml_configs/config_lorem_ipsum.yaml
The YAML configs are now being logged to weights and biases as artifacts.
> Config logging to W&B 

- src/modalities/evaluator.py
- src/modalities/trainer.py
This PR ensures that the model evaluation mode is properly deactivated after evaluation.
> fix: deactivation of model evaluation mode

- pyproject.toml
See [#124](https://github.com/Modalities/modalities/issues/124)
> Add Missing Dependency

- examples/getting_started/example_config.yaml
- examples/getting_started/example_text_generation_config.yaml
Update config files to reflect recent changes and make the getting started example work again
> Fix getting started example

- README.md
This PR introduces minor stylistic improvements to the README and adds additional badges to enhance the visual appearance and provide more information at a glance.
* Centered the title and badges for a more visually appealing layout.
* Added Python and PyTorch badges to showcase the technologies used.
* None
> Refactor: Improve Readme

- src/modalities/dataloader/dataloader_factory.py
This PR fixes the broken tests in main by check for fixed_num_batches is not None before comparison
* if statement
* None
> Fix broken tests in main.

- src/modalities/dataloader/open_gptx_dataset/mmap_dataset.py
- src/modalities/util.py
This PR moves the print_rank_0 function from a kind of legacy place towards a more central position.
* ..
* ..
> feat: moved print_rank_0 function towards a better fitting place

- src/modalities/config/component_factory.py
- src/modalities/optimizers/optimizer_factory.py
- src/modalities/running_env/fsdp/fsdp_auto_wrapper.py
- src/modalities/trainer.py
This PR improves logging on large scale distributed training by only printing on rank_0
* ..
* ..
> fix: improved readability by printing only on rank_0

- tests/utils/test_number_conversion.py
This PR fixes a [tiny linting issue](https://github.com/Modalities/modalities/actions/runs/10302572058/job/28516547406) caused by #213.
none
none
> Fix linting

- config_files/training/config_example_coca.yaml
- config_files/training/config_lorem_ipsum.yaml
- config_files/training/config_mamba_small.yaml
- examples/getting_started/example_config.yaml
- examples/library_usage/config_lorem_ipsum.yaml
- src/modalities/dataloader/dataloader_factory.py
- src/modalities/logging_broker/subscriber_impl/subscriber_factory.py
- tests/test_yaml_configs/coca_config_initialization.yaml
This PR makes sure that weights and biases logs everything (i.e., caching, logs etc.) within a single directory and respective subfolders. 
* see above
* none
> Wandb self contained offline logs

- src/modalities/trainer.py
- src/modalities/training/gradient_clipping/fsdp_gradient_clipper.py
- src/modalities/training/gradient_clipping/fsdp_gradient_clipper_config.py
- src/modalities/training/gradient_clipping/gradient_clipper.py
This PR adds docstrings to all files related to the training modules, enhancing code documentation and readability.
* 
* None
> Docstrings For Training Modules

- .github/pull_request_template.md
- config_files/training/config_example_coca.yaml
- config_files/training/config_lorem_ipsum.yaml
- config_files/training/config_mamba_small.yaml
- examples/getting_started/example_config.yaml
- examples/getting_started/run_getting_started_example.sh
- examples/library_usage/config_lorem_ipsum.yaml
- src/modalities/checkpointing/checkpoint_conversion.py
- src/modalities/checkpointing/checkpoint_loading.py
- src/modalities/checkpointing/checkpoint_saving.py
- src/modalities/checkpointing/checkpoint_saving_execution.py
- src/modalities/checkpointing/checkpoint_saving_instruction.py
- src/modalities/checkpointing/checkpoint_saving_strategies.py
- src/modalities/checkpointing/fsdp/fsdp_checkpoint_loading.py
- src/modalities/checkpointing/fsdp/fsdp_checkpoint_saving.py
- src/modalities/checkpointing/torch/torch_checkpoint_loading.py
- src/modalities/checkpointing/torch/torch_checkpoint_saving.py
- src/modalities/logging_broker/subscriber_impl/subscriber_factory.py
- src/modalities/util.py
- tests/run_distributed_tests.sh
- tests/test_utils.py
- tests/test_yaml_configs/coca_config_initialization.yaml
- tests/tests.py
- tests/utils/test_number_conversion.py
This PR adds docstrings to all files related to the checkpointing modules, enhancing code documentation and readability.
* 
* None
> Docstrings For Checkpointing

- src/modalities/__main__.py
- src/modalities/checkpointing/checkpoint_conversion.py
- src/modalities/config/component_factory.py
- src/modalities/config/config.py
- src/modalities/evaluator.py
- src/modalities/gym.py
- src/modalities/registry/components.py
- src/modalities/registry/registry.py
- src/modalities/running_env/cuda_env.py
- src/modalities/tokenization/tokenizer_wrapper.py
- src/modalities/utils/number_conversion.py
> Docstrings missing

- .github/workflows/tests_full.yml
> Update tests_full.yml to only support python 3.11

- .github/workflows/release_automation.yml
- pyproject.toml
> Release automation

- docs/dev_ops/release_procedure.md
> feat: added documentation on release management

- src/modalities/logging_broker/subscriber_impl/results_subscriber.py
This PR fixes the linting issues in main
* none
* none
> fix: linting (order of imports)

- tests/tests.py
This PR fixes paths in `tests.py` by renaming "examples" to "tutorials", as a follow-up to #254.
* ..
* ..
> Fix update path in tests.py

- .github/workflows/release_automation.yml
This PR aims to fix #272 by upgrading the gh-action-sigstore-python version
* ..
* ..
> update release automation

- .pre-commit-config.yaml
- src/modalities/api.py
- src/modalities/utils/logging.py
This PR adds policies on how to handle the situation when an indexation file already exists. 
* ..
* ..
> File existence policy for indexation

- src/modalities/config/config.py
- src/modalities/registry/components.py
This PR implementes the LinearLR sheduler (https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.LinearLR.html)
* ..
* ..
> feat: Added LinearLRScheduler as a new component

- src/modalities/config/instantiation_models.py
> feat: disentagle model and optimizer checkpoint loading

- tests/utils/test_mfu.py
This PR simulates different devices (A100 & H100) to generalize the MFU tests.
* None
* None
> MFU Test: simulate different devices

- .github/workflows/build_and_deploy_documentation.yml
- .github/workflows/release_automation.yml
- .github/workflows/tests_full.yml
This PR fixes some minor issues with github actions. 
In particular,
- the [failing build and deploy documentation workflow in the main branch](https://github.com/Modalities/modalities/actions/runs/13948994288/job/39063013296) is fixed
- the different github workflows now have a more similar structure
- the tests use `torch==2.6.0`
I manually checked that the github workflows [build and deploy documentation](https://github.com/Modalities/modalities/actions/runs/13964247272), [linting](https://github.com/Modalities/modalities/actions/runs/13964310255) and [tests](https://github.com/Modalities/modalities/actions/runs/13964352098) pass without errors. 
* None
* None
> Fix GitHub Actions

- src/modalities/inference/text/inference_component.py
- src/modalities/models/gpt2/pretrained_gpt_model.py
- src/modalities/models/huggingface/huggingface_model.py
- src/modalities/models/huggingface_adapters/hf_adapter.py
- src/modalities/models/model.py
- tests/checkpointing/test_checkpoint_conversion.py
- tests/checkpointing/test_fsdp_to_disc_checkpointing.py
- tests/test_evaluator.py
- tests/test_gym.py
- tests/test_lr_scheduler.py
This PR replaces `model.forward()` calls by `model()` calls.
* None
* None
> Callable instead of forward

- src/modalities/models/model_factory.py
- src/modalities/registry/components.py
This PR adds support for torch compile.
Need to check if this is still  compliant with torch compile best practices (check torch titan implementation and pytorch documentation)
* ..
* ..
> Torch compile

- tests/utils/test_experiment_id_generation.py
This PR adds a test for checking that the experiment id  is syned correctly across all ranks
* ..
* ..
> Experiment id syncing test

- config_files/training/config_lorem_ipsum_long_fsdp2.yaml
- src/modalities/__main__.py
- src/modalities/config/component_factory.py
- src/modalities/config/config.py
- src/modalities/config/instantiation_models.py
- src/modalities/config/pydanctic_if_types.py
- src/modalities/models/model_factory.py
- src/modalities/optimizers/optimizer_factory.py
- src/modalities/registry/components.py
- src/modalities/trainer.py
- src/modalities/util.py
- src/modalities/utils/mfu.py
- tests/config/test_component_factory.py
- tests/test_yaml_configs/config_lorem_ipsum.yaml
- tests/training/test_activation_checkpointing.py
This PR adds support for MFU calculation with FSDP2
* ..
* ..
> MFU calculation  support with FSDP2

- tests/test_gradient_clipping.py
This PR includes tests for FSDPXGradientClipper.
* ..
* ..
> test: added test for gradient clipping in fsdpX

- tests/test_initialization_fsdpx.py
> chore: improved weight init test making sure "other" group is empty

- tests/utils/test_mfu.py
This PR improves `test_mfu.py`. Related to https://github.com/Modalities/modalities/issues/364.
* None
* None
> Improvement of MFU test

- src/modalities/utils/mfu.py
This PR now adds MFU support for gh200 Nvidia gpus.
* ..
* ..
> feat: supports now gh200 mfu calculations

- src/modalities/conversion/gpt2/conversion_model.py
- src/modalities/conversion/gpt2/modeling_gpt2.py
- tests/conversion/gpt2/conftest.py
- tests/conversion/gpt2/test_conversion_model.py
* Update GPT2 modeling file to current version of transformer's llama modeling.
* Minor backwards compatibility in config conversion.
* Added test that an exception is thrown when a model with an unexpected key in its state dict is loaded.
> Updating and fixing conversion
